[package]
name = "pcaster"
version = "0.1.0"
edition = "2021"

[dependencies]
ebur128 = "0.1.10"
hound = "3.5.1"
plotters = "0.3.7"
rstest = "0.24.0"
symphonia = "0.5.4"

[dev-dependencies]
plotly = "0.11.0"
